# Docker compose that only uses public images
services:
  # Spring boot app cotainer
  web:
    build:
      context: ../entrega1
      dockerfile: ../docker/Dockerfile
    ports: 
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database/liveticket
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=LiveTicket
    depends_on:
      database:
        condition: service_healthy

  # Database container
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=LiveTicket
      - MYSQL_DATABASE=liveticket
    #We create a volume in the host to persist the information (as a folder at the level of the docker one)
    volumes:
      - ../mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5